ALTER TABLE recipes ADD COLUMN instructions TEXT;
ALTER TABLE recipes ADD COLUMN notes TEXT;
ALTER TABLE recipes ADD COLUMN sourceUrl TEXT;
ALTER TABLE recipes ADD COLUMN imageUrl TEXT;
ALTER TABLE recipes ADD COLUMN servings INTEGER;
ALTER TABLE recipes ADD COLUMN prepTimeMinutes INTEGER;
ALTER TABLE recipes ADD COLUMN cookTimeMinutes INTEGER;
ALTER TABLE recipes ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN createdAt TEXT;
ALTER TABLE recipes ADD COLUMN updatedAt TEXT;

